---
title: "Informe_2"
author: "Marco Ramirez, Estuardo Hernandez, Alfredo Quezada"
date: "2022-10-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Investigación de posibles algoritmos a utilizar

### Naive Bayes

El algoritmo clasificador Naïve-Bayes (NBC), es un clasificador probabilístico simple con fuerte suposición de independencia. Aunque la suposición de la independencia de los atributos es generalmente una suposición pobre y se viola a menudo para los conjuntos de datos verdaderos. A menudo proporciona una mejor precisión de clasificación en conjuntos de datos en tiempo real que cualquier otro clasificador. También requiere una pequeña cantidad de datos de entrenamiento. El clasificador Naïve-Bayes aprende de los datos de entrenamiento y luego predice la clase de la instancia de prueba con la mayor probabilidad posterior. También es útil para datos dimensionales altos ya que la probabilidad de cada atributo se estima independientemente.

Las ventajas del modelo Naive Bayes son:

- Fácil de implementar y aplicar a diferentes casos como la clasificación de texto.
- Naive Bayes requiere una pequeña cantidad de datos de entrenamiento para estimar los datos de las pruebas.
- Menos esfuerzo de preparación de datos.

Las desventajas del modelo Naive Bayes son:

- Tiene la fuerte hipótesis de independencia variable.
- Si la variable categórica tiene una categoría en el conjunto de datos de prueba, que no se observó en el conjunto de datos de entrenamiento, entonces el modelo asignará una probabilidad 0 (cero). En este caso, debe añadirse una unidad de cada conjunto de datos.

### Gaussian Naive Bayes

Uno de los tipos de clasificadores más populares es el llamado en inglés Gaussian Naive Bayes Classifier. Este toma en cuenta la probabilidad, la verosimilitud y la probabilidad marginal. Los nombres Gaussian y Naive del algoritmo vienen de dos suposiciones:
- Asumimos que las características de la verosimilitud no estan correlacionada entre ellas. Como no es siempre cierto y es una suposición ingenua es que aparece en el nombre “naive bayes”.
- Asumimos que el valor de las características tendrá una distribución normal (gaussiana). Esto nos permite calcular cada parte usando la función de probabilidad de densidad normal.

Las ventajas del modelo Gaussian Naive Bayes son:

- Es rápido.
- Es simple de implementar.
- Funciona bien con conjunto de datos pequeños.
- Va bien con muchas dimensiones (features).
- Llega a dar buenos resultados aún siendo “ingenuo” sin que se cumplan todas las condiciones de distribución necesarias en los datos.

Las desventajas del modelo Gaussian Naive Bayes son:

- Requiere quitar las dimensiones con correlación.
- Para buenos resultados las entradas deberían cumplir las 2 suposiciones de distribución normal e independencia entre sí (muy difícil que sea así ó deberíamos hacer transformaciones en lo datos de entrada).

### Multinomial Naive Bayes

El clasificador multinomial Naive Bayes es adecuado para la clasificación con características discretas, por ejemplo, recuento de palabras para la clasificación de texto. La distribución multinomial normalmente requiere recuentos de características de enteros. Sin embargo, en la práctica, los recuentos fraccionarios también pueden funcionar.

Se usa ampliamente para asignar documentos a clases en función del análisis estadístico de sus contenidos. Proporciona una alternativa al análisis semántico "pesado" basado en IA y simplifica drásticamente la clasificación de datos textuales. La clasificación tiene como objetivo asignar fragmentos de texto (es decir,
documentos) a clases determinando la probabilidad de que un documento pertenezca a la clase de otros documentos que tengan el mismo asunto.

### Bayesian Network

Es un modelo grafo probabilístico, un tipo de modelo estático, que representa un conjunto de variables aleatorias y sus dependencias condicionales a través de un grafo acíclico dirigido (DAG por sus siglas en inglés). Por ejemplo, una red bayesiana puede representar las relaciones probabilísticas entre enfermedades y síntomas. Dados los síntomas, la red puede ser usada para computar la probabilidad de la presencia de varias enfermedades.

Formalmente, las redes bayesianas son grafos dirigidos acíclicos cuyos nodos representan variables aleatorias en el sentido de Bayes: las mismas pueden ser cantidades observables, variables latentes, parámetros desconocidos o hipótesis. Las aristas representan dependencias condicionales; los nodos que no se encuentran conectados representan variables las cuales son condicionalmente independientes de las otras. Cada nodo tiene asociado una función de probabilidad que toma como entrada un conjunto particular de valores de las variables padres del nodo y devuelve la probabilidad de la variable representada por el nodo.

Las ventajas del modelo Bayesian Network son:

- La representación gráfica la convierte en una poderosa herramienta de comunicación, las relaciones causa-efecto se visualizan fácilmente sin la necesidad del cálculo de probabilidades.
- La posibilidad de combinar datos objetivos y subjetivos, esto es una enorme ventaja sobre todo cuando no se cuentan con suficientes datos estadísticos.
- Pueden modelar sistemas complejos.
- La red puede actualizarse rápidamente o modificarse por cambios en la información o un mal desempeño.
- Pueden utilizarse para anális de “Que pasa si”, para analizar la sensibilidad de las predicciones, o conclusiones respecto de los supuestos iniciales.

Las desventajas del modelo Bayesian Network son:

- Las Redes Bayesianas tienen la desventaja de que el modelo es bueno tanto como el que modela lo sea y la percepción que tengan los expertos de la realidad.
- Otra limitación se relaciona con el hecho de que la utilidad de las RBs está basada en la confiabilidad de la información a priori. Un expectativa demasiado optimista o pesimista de las creencias a priori pueden ya sea distorsionar la red o invalidar los resultados. Seleccionar una apropiada distribución de los datos tiene un importante efecto en la calidad de los resultados de la red.

## Algoritmos y modelos seleccionados

Naive Bayes.

## Construcción de modelos



## Prueba de los modelos



## Discusión

Ambos modelos son muy similares en cuanto a los resultados, tienen la misma precisión a la hora de predecir excepto al clasificar argumentos ineficaces, el primer modelo arroja una precisión de 35% y el segundo un 34%, sigue siendo una precisión muy similar. Para argumentos adecuados y efectivos se obtuvo precisiones de 65% y 60% en ambos modelos. Se comprueba que el algoritmo de Naive Bayes es eficaz en la aplicación de clasificación de textos sin necesidad de muchos recursos.

Los NBC escalan muy bien, lo que significa que podemos agregar muchas más funciones y el algoritmo seguirá siendo rápido y confiable. Incluso en el caso de que los NBC no fueran adecuados para el problema que se está tratando de resolver, podrían ser útiles como referencia.

## Visualizaciones estáticas


